export { default as Facebook } from './Facebook'
export { default as Magnifier } from './Magnifier'
export { default as Bell } from './Bell'
export { default as Download } from './Download'
export { default as Person } from './Person'
